const q = [
    'If a dozen other companies are creating a company right now with this exact idea, how could you still succeed?',
    'Who were your first customers?',
    'How close do you feel you are to product-market fit? (Here, its less that we want you to have product-market fit, and more that we want to understand how you think about your own progress wherever you are.)',
    'Are there any plans you really would like to pursue, but have stopped talking about with investors because youve been told by VCs they are bad ideas? (We often like those plans.)',
    'If youre successful, what potential harms might your service cause, and what will you do about that? ',
    'Whats been the most difficult ethical dilemma youve had at work?',
    'For what values would you sacrifice making more money?',
    'In practice, have you sacrificed financially to live by a principle?',
    'How will you build a diverse and inclusive team over the next year?',
    'Given your personalities, what culture issues do you think are most likely to arise at your company',
    'Why are you raising money at all?',
    'How does this person compare to other founders you’ve known? Top 10%? 5%? 1%?',
    'What makes you believe this person is extraordinary?',
    'Do you trust this person?',
    'If you were us, and decided to invest in the company, in what areas would you guess this person would need the most help?',
    'Ever do something singular? Record of unusual achievement',
    'Best-in-the-world domain experience or punch-way-above-your-weight-class first hires',
    'Depth of commitment to the problem ("would do this for a decade, and keep going even if funding never appeared"), especially in learning the domain',
    'Would you work for the team?',
    'Do any users love the product so much they spontaneously tell other people to use it?',
    'A wow of a product experience and/or extreme early growth and engagement numbers (for products adopted by individuals)',
    'Customers dont need to be sold, want to pay full-price immediately -> evangelists (for products adopted by companies)',
    'Do you have an exclusive path to customers -- distribution as a competitive advantage',
    'How many people do you intend to hire, where will you spend the money?',
    'What is your user growth like?',
    'What is your MRR?',
    'How many people do you intend to hire, where will you spend the money?',
    'What is your monthly plan for the next twelve months?',
    'What is your quarterly plan for the next two years?',
    'How does your company make work more productive, fulfilling, inclusive, and available?',
    'How does your company make your client’s work look more like a developer’s or securities trader’s?',
    'How is your product the most important service to your users?',
    'How do you sell? (looking for one model)',
    'Who is the one person you’re targeting?',
    'How do you know your customers love you?',
    'What makes you an outlier? (Do you know what makes your company a potential outlier?)',
    'Why is this problem important to you, and how will things be better if you succeed?',
    'What was the last important skill you learned? (We believe great founders are, paradoxically, both self-confident and exceptionally good learners -- so constantly in need of improvement.)',
    'What was the last thing you were wrong about?',
    'What do you want out of your investors other than money? (We’re trying to figure out if we can be uniquely helpful.)',
]
